### ISSUE TITLE
Clarifying release procedure

### ISSUE THREAD

**Issue by ldodds** [theodi/open-standards-guidebook#45]
@tomdavies can you step me through the release procedure, I've made a mistake somewhere.

I just ran the release script to release 0.0.1.

I got this:

```
/home/ldodds/workspaces/theodi/open-standards-guidebook
Starting release 0.0.1
Branches 'develop' and 'origin/develop' have diverged.
And local branch 'develop' is ahead of 'origin/develop'.
Switched to a new branch 'release/0.0.1'

Summary of actions:
- A new branch 'release/0.0.1' was created, based on 'develop'
- You are now on branch 'release/0.0.1'

Follow-up actions:
- Bump the version number now!
- Start committing last-minute fixes in preparing your release
- When done, run:

     git flow release finish '0.0.1'

Updating VERSION
On branch release/0.0.1
nothing to commit, working directory clean
Finishing release 0.0.1
./scripts/release: line 23: version: command not found
Branches 'master' and 'origin/master' have diverged.
Fatal: And branch 'master' may be fast-forwarded.
husky > pre-push (node v8.9.4)
yarn run v1.5.1
$ yarn lint-styles && yarn lint-js
$ yarn sass-lint -v
$ /home/ldodds/workspaces/theodi/open-standards-guidebook/node_modules/.bin/sass-lint -v
$ yarn eslint -o ./linters/eslint.html assets/js/
$ /home/ldodds/workspaces/theodi/open-standards-guidebook/node_modules/.bin/eslint -o ./linters/eslint.html assets/js/
Done in 3.73s.
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 262 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To git@github.com:theodi/open-standards-guidebook.git
 * [new branch]      release/0.0.1 -> release/0.0.1
Branch release/0.0.1 set up to track remote branch release/0.0.1 from origin.
Already on 'release/0.0.1'
Your branch is up-to-date with 'origin/release/0.0.1'.

Summary of actions:
- The remote branch 'release/0.0.1' was created or updated
- The local branch 'release/0.0.1' was configured to track the remote branch
- You are now on branch 'release/0.0.1'
```

Note the error messages. Am not sure if this was down to wrong version of git flow, or that my master branch wasn't up to date? Or both. Any ideas?

Git flow version (installed via `apt-get`) is `1.9.1 (AVH Edition)`

I assume I can just delete that branch and then retry, but will hold fire for now.

Am assuming that once these errors are resolved, it will have merged the release branch and pushed master to trigger the deploy.

**Comment by tomdavies** [comment]
@ldodds I think this is potentially as simple as needing to `git pull` before you run the release script - note the `Branches 'develop' and 'origin/develop' have diverged.` as well.

I will update the script to force a pull first

**Comment by ldodds** [comment]
I deleted my local and the remote release 0.0.1 branches. I've just pulled down latest code and re-run the script using 0.0.2.

The final message from the script is "Fatal: Branch 'release/0.0.2' does not exist and is required."

It appears to have pushed and merged the branches and it triggered travis build. Just checking whether the updated content is in place.

Full output is below. 

```
/home/ldodds/workspaces/theodi/open-standards-guidebook
Starting release 0.0.2
Switched to a new branch 'release/0.0.2'

Summary of actions:
- A new branch 'release/0.0.2' was created, based on 'develop'
- You are now on branch 'release/0.0.2'

Follow-up actions:
- Bump the version number now!
- Start committing last-minute fixes in preparing your release
- When done, run:

     git flow release finish '0.0.2'

Updating VERSION
[release/0.0.2 ef175be] 0.0.2 release
 1 file changed, 1 insertion(+), 1 deletion(-)
Finishing release 0.0.2
./scripts/release: line 23: version: command not found
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Removing src/creating-open-standards/managing-change/index.md
Removing src/creating-open-standards/how-to-use-the-open-standards-for-data-canvas/open-standards-for-data.pdf
Removing src/creating-open-standards/how-to-use-the-open-standards-for-data-canvas/gtfs-example.pdf
Removing assets/js/vendor/barefoot.js
Removing assets/js/helpers/dom-helper.js
Merge made by the 'recursive' strategy.
 .eslintrc.js                                                                                          |   3 +-
 .gitignore                                                                                            |   2 +-
 .huskyrc                                                                                              |   3 +
 .sass-lint.yml                                                                                        |   2 +-
 .travis.yml                                                                                           |   3 +
 README.md                                                                                             |  45 ++++++++---
 VERSION                                                                                               |   2 +-
 _config.yml                                                                                           |   3 +-
 assets/components/atoms/aside/_aside.scss                                                             |   7 +-
 assets/components/atoms/blockquote/_blockquote.scss                                                   |  10 ++-
 assets/components/atoms/list/_list.scss                                                               |  29 +++++++-
 assets/components/atoms/table/_table.scss                                                             | 118 ++++++++++++++---------------
 assets/components/forms/checkbox/_checkbox.scss                                                       |   4 +-
 assets/components/main.scss                                                                           |   4 +-
 assets/components/molecules/hero-home/_hero-home.scss                                                 |   6 +-
 assets/js/helpers/dom-helper.js                                                                       |   7 --
 assets/js/main.js                                                                                     |   4 +-
 assets/js/modules/ajaxForm.js                                                                         |  29 ++++----
 assets/js/modules/eventTracking.js                                                                    |  30 ++++----
 assets/js/modules/modals.js                                                                           |   8 +-
 assets/js/modules/toggle.js                                                                           |  12 ++-
 assets/js/vendor/barefoot.js                                                                          | 388 -----------------------------------------------------------------------------------------------
 build/task-config.js                                                                                  |   4 +-
 package.json                                                                                          |   7 +-
 src/404.html                                                                                          |  13 +++-
 src/_includes/breadcrumbs.html                                                                        |   4 +-
 src/_includes/download-links.html                                                                     |  26 ++++---
 src/_includes/favicons.html                                                                           |  38 +++++-----
 src/_includes/footer.html                                                                             |   2 +-
 src/_includes/hero-home.html                                                                          |   2 +-
 src/_includes/lede.html                                                                               |   2 +-
 src/_includes/masthead.html                                                                           |  10 +--
 src/_includes/section-listing.html                                                                    |   2 +-
 src/_includes/section-nav.html                                                                        |   4 +-
 src/_includes/sidebar-sections.html                                                                   |  12 +--
 src/_layouts/application.html                                                                         |   7 +-
 src/_layouts/case-study.html                                                                          |   8 +-
 src/_layouts/content-page.html                                                                        |  10 ++-
 src/_layouts/infographic.html                                                                         |   8 +-
 src/_layouts/podcast.html                                                                             |  31 ++++----
 src/community/case-studies/index.md                                                                   |   6 ++
 src/community/{example-podcast => community-voices}/edafe.jpg                                         | Bin
 src/community/{example-podcast => community-voices}/index.md                                          |   0
 src/community/who-can-i-work-with/index.md                                                            |   8 ++
 src/community/who-can-i-work-with/open-data-services.md                                               |   6 ++
 src/community/who-can-i-work-with/porism.md                                                           |   6 ++
 src/community/who-can-i-work-with/w3c.md                                                              |   6 ++
 src/creating-impact/economic-impacts.md                                                               |  10 +--
 src/creating-impact/getting-started.md                                                                | 116 ++++++++++++++++++++---------
 src/creating-impact/lessons-learned-in-open-standards-development.md                                  | 148 +++++++++++++++++++++++++++++++++++-
 src/creating-impact/policy-impacts.md                                                                 |  10 +--
 src/creating-impact/social-impacts.md                                                                 |  12 +--
 src/creating-impact/technology-impacts.md                                                             | 105 +++++++++++++++++++++++++-
 src/creating-open-standards/data-ecosystem-mapping-for-open-standards/index.md                        |   8 ++
 src/creating-open-standards/developing-standards/index.md                                             |   2 +-
 src/creating-open-standards/getting-started.md                                                        | 175 ++++++++++++++++++++++++++++++++++++++++++-
 src/creating-open-standards/how-to-set-up-a-w3c-community-group/index.md                              |  59 +++++++++++++++
 src/creating-open-standards/how-to-use-the-open-standards-for-data-canvas/gtfs-example.pdf            | Bin 79511 -> 0 bytes
 src/creating-open-standards/how-to-use-the-open-standards-for-data-canvas/index.md                    |   5 +-
 src/creating-open-standards/how-to-use-the-open-standards-for-data-canvas/open-standards-for-data.pdf | Bin 46693 -> 0 bytes
 src/creating-open-standards/managing-change-in-open-standards.md                                      | 173 ++++++++++++++++++++++++++++++++++++++++++
 src/creating-open-standards/managing-change/index.md                                                  |   5 --
 src/creating-open-standards/typical-outputs-for-developing-open-standards-checklist/index.md          |   2 +
 src/find-existing-standards/how-to-choose-an-open-standard-checklist.md                               |   7 ++
 src/find-existing-standards/how-to-choose-an-open-standard.md                                         |   7 ++
 src/find-existing-standards/how-to-find-open-standards.md                                             |   7 +-
 src/find-existing-standards/index.md                                                                  |  23 +++++-
 src/find-existing-standards/tools-to-find-open-standards.md                                           |  47 ++++++++----
 src/introduction/how-open-standards-are-developed.md                                                  | 146 +++++++++++++++++++++++++++++++++++-
 src/introduction/how-to-make-the-case-for-open-standards.md                                           |   7 ++
 src/introduction/index.md                                                                             |   5 +-
 src/introduction/stages-in-standards-development-open-data-institute.jpg                              | Bin 0 -> 150547 bytes
 src/introduction/types-of-open-standards-for-data.md                                                  |  10 +--
 src/introduction/what-are-open-standards-for-data.md                                                  |  14 ++--
 src/introduction/when-not-to-create-new-standards.md                                                  |  16 ++--
 src/introduction/when-to-use-open-standards-for-data.md                                               |  12 +--
 yarn.lock                                                                                             |  78 ++++++++++++++++++-
 77 files changed, 1431 insertions(+), 719 deletions(-)
 create mode 100644 .huskyrc
 delete mode 100644 assets/js/helpers/dom-helper.js
 delete mode 100644 assets/js/vendor/barefoot.js
 create mode 100644 src/community/case-studies/index.md
 rename src/community/{example-podcast => community-voices}/edafe.jpg (100%)
 rename src/community/{example-podcast => community-voices}/index.md (100%)
 create mode 100644 src/community/who-can-i-work-with/index.md
 create mode 100644 src/community/who-can-i-work-with/open-data-services.md
 create mode 100644 src/community/who-can-i-work-with/porism.md
 create mode 100644 src/community/who-can-i-work-with/w3c.md
 create mode 100644 src/creating-open-standards/data-ecosystem-mapping-for-open-standards/index.md
 create mode 100644 src/creating-open-standards/how-to-set-up-a-w3c-community-group/index.md
 delete mode 100644 src/creating-open-standards/how-to-use-the-open-standards-for-data-canvas/gtfs-example.pdf
 delete mode 100644 src/creating-open-standards/how-to-use-the-open-standards-for-data-canvas/open-standards-for-data.pdf
 create mode 100644 src/creating-open-standards/managing-change-in-open-standards.md
 delete mode 100644 src/creating-open-standards/managing-change/index.md
 create mode 100644 src/find-existing-standards/how-to-choose-an-open-standard-checklist.md
 create mode 100644 src/find-existing-standards/how-to-choose-an-open-standard.md
 create mode 100644 src/introduction/how-to-make-the-case-for-open-standards.md
 create mode 100644 src/introduction/stages-in-standards-development-open-data-institute.jpg
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
Merge made by the 'recursive' strategy.
 VERSION | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
Deleted branch release/0.0.2 (was ef175be).
husky > pre-push (node v8.9.4)
yarn run v1.5.1
$ yarn lint-styles && yarn lint-js
$ yarn sass-lint -v
$ /home/ldodds/workspaces/theodi/open-standards-guidebook/node_modules/.bin/sass-lint -v
$ yarn eslint -o ./linters/eslint.html assets/js/
$ /home/ldodds/workspaces/theodi/open-standards-guidebook/node_modules/.bin/eslint -o ./linters/eslint.html assets/js/
Done in 3.31s.
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 558 bytes | 0 bytes/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 1 local object.
To git@github.com:theodi/open-standards-guidebook.git
   c270bbd..cc0928b  develop -> develop
husky > pre-push (node v8.9.4)
yarn run v1.5.1
$ yarn lint-styles && yarn lint-js
$ yarn sass-lint -v
$ /home/ldodds/workspaces/theodi/open-standards-guidebook/node_modules/.bin/sass-lint -v
$ yarn eslint -o ./linters/eslint.html assets/js/
$ /home/ldodds/workspaces/theodi/open-standards-guidebook/node_modules/.bin/eslint -o ./linters/eslint.html assets/js/
Done in 3.24s.
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:theodi/open-standards-guidebook.git
   fb430c1..3448db5  master -> master
husky > pre-push (node v8.9.4)
yarn run v1.5.1
$ yarn lint-styles && yarn lint-js
$ yarn sass-lint -v
$ /home/ldodds/workspaces/theodi/open-standards-guidebook/node_modules/.bin/sass-lint -v
$ yarn eslint -o ./linters/eslint.html assets/js/
$ /home/ldodds/workspaces/theodi/open-standards-guidebook/node_modules/.bin/eslint -o ./linters/eslint.html assets/js/
Done in 3.25s.
Counting objects: 1, done.
Writing objects: 100% (1/1), 156 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To git@github.com:theodi/open-standards-guidebook.git
 * [new tag]         0.0.2 -> 0.0.2

Summary of actions:
- Release branch 'release/0.0.2' has been merged into 'master'
- The release was tagged '0.0.2'
- Release tag '0.0.2' has been back-merged into 'develop'
- Release branch 'release/0.0.2' has been locally deleted
- 'develop', 'master' and tags have been pushed to 'origin'
- You are now on branch 'develop'

Fatal: Branch 'release/0.0.2' does not exist and is required.
```

**Comment by tomdavies** [comment]
@ldodds I think that's just git flow trying to delete the remote release branch, which does not exist as it gets merged and deleted before ever being pushed, hence the error. I will look at the release script, but in the short term, nothing to worry about!

**Comment by ldodds** [comment]
@tomdavies am still convinced something is not quite right, or I'm doing something wrong:

```
ldodds@dawn:~/workspaces/theodi/open-standards-guidebook$ ./scripts/release 0.0.3
Checking for clean working tree
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
From github.com:theodi/open-standards-guidebook
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
Update from origin remote
Fetching origin
Checking up to date with remote
Up-to-date
Starting release 0.0.3
Switched to a new branch 'release/0.0.3'

Summary of actions:
- A new branch 'release/0.0.3' was created, based on 'develop'
- You are now on branch 'release/0.0.3'

Follow-up actions:
- Bump the version number now!
- Start committing last-minute fixes in preparing your release
- When done, run:

     git flow release finish '0.0.3'

Updating VERSION
[release/0.0.3 d53be7f] 0.0.3 release
 1 file changed, 1 insertion(+), 1 deletion(-)
Finishing release 0.0.3
./scripts/release: line 63: version: command not found
Fatal: Branch 'release/v.' does not exist and is required.
husky > pre-push (node v8.10.0)
yarn run v1.5.1
$ yarn lint-styles && yarn lint-js
$ yarn sass-lint -v
$ /home/ldodds/workspaces/theodi/open-standards-guidebook/node_modules/.bin/sass-lint -v
$ yarn eslint -o ./linters/eslint.html assets/js/
$ /home/ldodds/workspaces/theodi/open-standards-guidebook/node_modules/.bin/eslint -o ./linters/eslint.html assets/js/
Done in 7.13s.
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 264 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To git@github.com:theodi/open-standards-guidebook.git
 * [new branch]      release/0.0.3 -> release/0.0.3
Branch release/0.0.3 set up to track remote branch release/0.0.3 from origin.
Already on 'release/0.0.3'
Your branch is up-to-date with 'origin/release/0.0.3'.

Summary of actions:
- The remote branch 'release/0.0.3' was created or updated
- The local branch 'release/0.0.3' was configured to track the remote branch
- You are now on branch 'release/0.0.3'
```

This triggers a build in travis for 0.0.3 branch, but doesn't seem to merged to master or triggered a build and deploy.

**Comment by tomdavies** [comment]
@ldodds should be fixed by e13724a - let me know if not!

**Comment by ldodds** [comment]
@tomdavies still having a few problems with this. 

Now when I run the script it appears to do the necessary merging, but its not pushing anything upstream. Having just run `./script/release 0.8` I got the output below. 

Nothing triggered on travis until I did a manual `git push` at the end, is that the expected behaviour?

The release branch hasn't been pushed to github either.

```
Checking for clean working tree
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
From github.com:theodi/open-standards-guidebook
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
From github.com:theodi/open-standards-guidebook
 * branch            master     -> FETCH_HEAD
Already up-to-date!
Merge made by the 'recursive' strategy.
Update from origin remote
Fetching origin
Checking up to date with remote
Up-to-date
Starting release 0.8
Branches 'develop' and 'origin/develop' have diverged.
And local branch 'develop' is ahead of 'origin/develop'.
Switched to a new branch 'release/0.8'

Summary of actions:
- A new branch 'release/0.8' was created, based on 'develop'
- You are now on branch 'release/0.8'

Follow-up actions:
- Bump the version number now!
- Start committing last-minute fixes in preparing your release
- When done, run:

     git flow release finish '0.8'

Updating VERSION
[release/0.8 6502a7d] 0.8 release
 1 file changed, 1 insertion(+), 1 deletion(-)
Finishing release 0.8
Branches 'develop' and 'origin/develop' have diverged.
And local branch 'develop' is ahead of 'origin/develop'.
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Removing src/creating-open-standards/developing-standards/introduction.md
Removing docs/spacing.config.js
Removing docs/grid.config.js
Removing docs/colour-palette.config.js
Merge made by the 'recursive' strategy.
 .gitignore                                                                         |   1 +
 .travis.yml                                                                        |   1 +
 ODI OSD.sublime-project                                                            |   6 ++-
 Rakefile                                                                           |   9 ++--
 VERSION                                                                            |   2 +-
 _config.dev.yml                                                                    |   2 +-
 a.out                                                                              | Bin 0 -> 1832 bytes
 breakpoints.yml                                                                    |   0
 build/task-config.js                                                               |   4 +-
 colours.yml                                                                        |   0
 docs/colour-palette.config.js                                                      |  21 ----------
 docs/grid.config.js                                                                |  21 ----------
 docs/spacing.config.js                                                             |  21 ----------
 fontsizes.yml                                                                      |   0
 scripts/release                                                                    |   6 +--
 spacing.yml                                                                        |   0
 src/_includes/hero-home.html                                                       |   2 +-
 src/creating-impact/economic-impacts.md                                            |   4 +-
 src/creating-impact/getting-started.md                                             |  16 ++++----
 src/creating-impact/lessons-learned-in-open-standards-development.md               |  26 ++++++------
 src/creating-impact/policy-impacts.md                                              |   2 +-
 src/creating-impact/technology-impacts.md                                          |   8 ++--
 src/creating-open-standards/developing-standards/development.md                    | 257 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 src/creating-open-standards/developing-standards/index.md                          |  18 +++++++-
 src/creating-open-standards/developing-standards/introduction.md                   |   8 ----
 src/creating-open-standards/developing-standards/launch-and-adoption.md            | 152 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 src/creating-open-standards/developing-standards/review.md                         | 164 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 src/creating-open-standards/developing-standards/scoping-and-starting.md           | 188 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 src/creating-open-standards/developing-standards/update-or-retire.md               | 153 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 src/creating-open-standards/getting-started.md                                     |  16 ++++----
 src/creating-open-standards/how-to-set-up-a-w3c-community-group/index.md           |   6 +--
 src/creating-open-standards/how-to-use-the-open-standards-for-data-canvas/index.md |   6 +--
 src/creating-open-standards/managing-change-in-open-standards.md                   |   8 ++--
 src/find-existing-standards/how-to-choose-an-open-standard-checklist.md            |  61 ++++++++++++++++++++++++++-
 src/find-existing-standards/how-to-choose-an-open-standard.md                      | 121 +++++++++++++++++++++++++++++++++++++++++++++++++++++-
 src/find-existing-standards/how-to-find-open-standards.md                          |  74 ++++++++++++++++++++++++++++++++-
 src/find-existing-standards/tools-to-find-open-standards.md                        |   6 ---
 src/introduction/how-open-standards-are-developed.md                               |  14 +++----
 src/introduction/stages-in-standards-development-open-data-institute.jpg           | Bin 150547 -> 840998 bytes
 src/introduction/we-can-standardise-open-data-institute.jpg                        | Bin 213143 -> 638397 bytes
 40 files changed, 1245 insertions(+), 159 deletions(-)
 create mode 100755 a.out
 create mode 100644 breakpoints.yml
 create mode 100644 colours.yml
 delete mode 100644 docs/colour-palette.config.js
 delete mode 100644 docs/grid.config.js
 delete mode 100644 docs/spacing.config.js
 create mode 100644 fontsizes.yml
 create mode 100644 spacing.yml
 delete mode 100644 src/creating-open-standards/developing-standards/introduction.md
Switched to branch 'develop'
Your branch is ahead of 'origin/develop' by 3 commits.
  (use "git push" to publish your local commits)
Merge made by the 'recursive' strategy.
 VERSION | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
Deleted branch release/0.8 (was 6502a7d).

Summary of actions:
- Release branch 'release/0.8' has been merged into 'master'
- The release was tagged '0.8'
- Release tag '0.8' has been back-merged into 'develop'
- Release branch 'release/0.8' has been locally deleted
- You are now on branch 'develop'

Fatal: Branch 'release/0.8' does not exist and is required.
```

**Comment by tomdavies** [comment]
@ldodds there was a bug, which I've just fixed, but you should also be manually doing a git pull before running a release to make sure you're actually deploying the latest code as pushed to GH. Thats why you were seeing:

```
Branches 'develop' and 'origin/develop' have diverged.
And local branch 'develop' is ahead of 'origin/develop'.
```

**Comment by tomdavies** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issues with release script](https://trello.com/c/GeMq7dAZ/154-issues-with-release-script)

**Comment by ldodds** [comment]
I've run the script again.

I still get the error at the end when it tries to do the final step: `git flow publish` which I can't see will ever work as `finish` is done in the previous step. Why is it there?

This also still doesn't actually push any of the merged code up to github. So had to do `git push` again to push both the develop and master branches. This then triggers the builds and the actual release.

So I think either script needs a git push at the end instead of a `git flow publish` or the docs need to reflect that there's two steps?

**Comment by tomdavies** [comment]
@ldodds please could you pull and test again?

I disabled the `-p` (push) flag on the command to finish the release when debugging the script (so as to not accidentally publish dummy releases) and forgot to re-add it before committing the last fix.

If that doesn't work, could you also post the output of running `git flow version` locally.

**Comment by ldodds** [comment]
:+1: 

thanks!
